const real = `..................................D...............
..o.............................D..............b..
.H....o........z...........D......................
.......................Y...O............1.........
......4...............N....................d......
........4......................D..........d.......
.o.............4................1.................
.......................................y.1......w.
..........Y.H..........5.........y.......b........
...Q.....H......Y...............y..m..............
.........Q.Y..............O..................m....
............................N...O.................
....5.............................8...........b...
....H....................................w........
.........................1.....O..y.........d.....
.........................4........................
...............................2..................
........Q...5.....................................
..............0...................................
.....................0...Z...2....................
.....0.........................MZ.m...............
...6........0...........Z.....m..................d
.................................B.E..............
......6...........................................
.......................................8..B.......
..z......5.............................7.....8....
..................................................
......................................2...........
.........Z..6....................q................
..................................................
.......6.................G..7.....................
.......z................I.....b.B...............e.
.........N..............................2...M.....
..G...............................................
...................w...g.....7......E.............
...........................q...n..........M.E.....
........................................I.........
................................W.......7..e......
..........................9....................W..
...............G.3..8..............B.9.......i....
..................................n..............3
....................3................E............
............................3........h..i.........
....................9......hi...............n..M..
..............z..............I....h..............i
..............h............g......................
....................G..............e..............
...............................I............g.....
................q...g..9..........e...W......n....
.......................................W..........`;

const test = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
`;

const test2 = `..........
..........
..........
....a.....
..........
.....a....
..........
..........
..........
..........`;

const p2Test = `T.........
...T......
.T........
..........
..........
..........
..........
..........
..........
..........`;

const getNumThings = (input: string) => {
  const allRows = input.split("\n").map((r) => r.split(""));
  const xLength = allRows[0].length;
  const yLength = allRows.length;

  const { signalCoords, signalPositions } = allRows.reduce<{
    signalCoords: Map<string, [number, number][]>;
    signalPositions: Set<string>;
  }>(
    (acc, row, y) => {
      for (let x = 0; x < row.length; x++) {
        const item = row[x]!;
        if (item === ".") continue;
        if (acc.signalCoords.has(item)) {
          acc.signalCoords.get(item)!.push([x, y]);
        } else {
          acc.signalCoords.set(item, [[x, y]]);
        }
        acc.signalPositions.add(JSON.stringify([x, y]));
      }
      return acc;
    },
    { signalCoords: new Map(), signalPositions: new Set() }
  );
  const hashThings = new Set<string>();
  const cantgohere = [];

  const addPoint = (point: [number, number]) => {
    const [x, y] = point;

    if (x < 0 || x >= xLength || y < 0 || y >= yLength) {
      cantgohere.push({
        x,
        y,
        thingHere: allRows[y]?.[x],
        has: signalPositions.has(JSON.stringify(point)),
      });
      return false;
    }
    hashThings.add(JSON.stringify(point));
    return true;
  };

  for (const [_signal, positions] of signalCoords) {
    // permutations of positions

    // when spot is both in the input and

    for (let i = 0; i < positions.length; i++) {
      for (let j = 0; j < positions.length; j++) {
        if (j === i) continue;

        const firstPoint = positions[i];
        const otherPoint = positions[j];

        // the top one we want to subtract y from
        // the left one we want to subtract x from
        // vise versa

        const dx = otherPoint[0] - firstPoint[0];
        const dy = otherPoint[1] - firstPoint[1];

        // Calculate the two antinode points
        let attempt = 0;
        while (
          addPoint([firstPoint[0] - dx * attempt, firstPoint[1] - dy * attempt])
        ) {
          attempt++;
        }
      }
    }
  }

  for (const thing of hashThings) {
    const [x, y] = JSON.parse(thing);
    if (allRows[y][x] !== ".") {
      console.log("On Antenna:", {
        x,
        y,
        xLength,
        yLength,
        thing: allRows[y][x],
      });
    }
    if (allRows[y][x] === ".") {
      allRows[y][x] = "#";
    }
  }
  const resString = allRows.map((r) => r.join("")).join("\n");
  console.log(resString);
  console.log(hashThings.size);
};

// overwrote part 1 with part 2 - ( •_•)>⌐■-■ (⌐■_■)

getNumThings(real);
